version: '3.8' # Versión de la sintaxis de Docker Compose

services:
  apache-server:
    build:
      context: ./apache-config
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./web-page:/var/www/html
    networks:
      - platzinet
      
  app-temp:
    build: 
      context: ./my-web-api
      dockerfile: Dockerfile
    depends_on:
      - tuTiendaDB
    ports:
      - 8000:8000
    volumes:
      - ./my-web-api:/web-server
    networks:
      - platzinet

  tuTiendaDB:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - dbAppTienda:/data/db
    networks:
      - platzinet
    
    
networks:
  platzinet:
    external: True

volumes: # <--- YOU NEED TO DEFINE THE NAMED VOLUME HERE
  dbAppTienda: # <--- This declares the 'dbAppTienda' volume

