services:
  app-temp:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - tuTiendaDB
    ports:
      - 8000:8000
    volumes:
      - .:/web-server
    networks:
      - platzinet

  tuTiendaDB:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - dbAppTienda:/data/db
    networks:
      - platzinet
    
    
networks:
  platzinet:
    external: True

volumes: # <--- YOU NEED TO DEFINE THE NAMED VOLUME HERE
  dbAppTienda: # <--- This declares the 'dbAppTienda' volume

